# Based on https://medium.com/@olebedev/live-code-reloading-for-golang-web-projects-in-19-lines-8b2e8777b1ea
PID = /tmp/{{.project_name}}.pid

serve: restart
	@fswatch -e '.*assets.go' -e '.*bindata.go' -o . | xargs -n1 -I{}  make restart || make kill

kill:
	@kill `cat $(PID)` || true

before:
	@echo "Generate assets"
	@go generate
	@echo "Build binary"
	@go build -o /tmp/{{.project_name}} {{.project_name}}.go

restart: kill before
	 @/tmp/{{.project_name}} server -b localhost -p 5000 & echo $$! > $(PID)

.PHONY: serve restart kill before # let's go to reserve rules names
